"""Initial database

Revision ID: 124903fa4c53
Revises: 
Create Date: 2019-10-13 20:31:54.318702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124903fa4c53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ClassRoom',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('student_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_ID'], ['Students.id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('Subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('student_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_ID'], ['Students.id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subjects')
    op.drop_table('ClassRoom')
    op.drop_table('Students')
    # ### end Alembic commands ###
